campaign: CircBrazil
campaign_id: CircBrazil
platform: R/V Sonne
location: Atlantic
configs:
    main: config/main.yaml  # name of this file
    level0: config/level0_mwx.yml
    level1: config/level1.yaml
    level2: config/level2.yaml
